Lichess4545/Chesster

- .gitignore
- Vagrantfile
- chesster.js
- start
- start_debug
- vagrant-dependencies.sh
This uses levenshtein distance of the strings and some regexes to make the commands more resilient. It also uses the channel name to determine which tournament is appropriate.
Only the mods command has been improved in this way, but the facilities should be easily ported to other commands.
> Initial work on fuzzy matching

- chesster.js
- spreadsheets.js
- test/test_spreadsheets.js
no hurry on this.
its working as is, but this is for consistency
> replace date with moment and fix gamelink parsing when it comes in as markup

- chesster.js
- player.js
This fixes #21 and #32.  I factored out the code to pull a player id so we can generate commands that take players as an argument and it should work with:
player
@player
playerMixedCase
aj;sldfkajs;dlfkj (garbage)
<blank>
> Fixes because typo and rating @<player> syntax

- spreadsheets.js
This fixes #25. (or make the algorithm something I'm more happy with)
> Fixing this algorithm to be a bit more elegant.

- .gitignore
- chesster.js
In this pull request:
1. replaced error_log with stderr.
2. fetching json from a url will now return the json object, potenially undefined, and an error. I wanted to do this using exceptions, but because of the callbacks, that was not possible.
3. where the function is used, I check the result of the json and if not defined, then write the error to the logs and handle the error.
4. added color to pairings.
5. I refectactored some of the pairing code while I was handling the errors and colors.
> Some defense

- chesster.js
Just added the three new mods un prepareModsMessage() and prepareSummonModsMessage() . Was there any other place I needed to update?
> Updating Mod List

- .gitignore
- chesster.js
> add stalemate status to valid result scenarios

- .eslintrc
- README.md
- config/config.js
- package.json
- src/chesster.js
- src/league.js
- src/lichess.js
- src/slack.js
- src/spreadsheets.js
- src/subscription.js
- test/test_league.js
Changed everything over from underscore to lodash and also refactored a bit.
> Switch to lodash

- config/config.js
Did the same thing as it was prior (links to the Slack file. Not sure if we want this, or want a direct link to the sheet?)
> Link (team) needed to be updated

- .gitignore
- src/chesster.js
- src/spreadsheets.js
(1) emits a-game-starts and a-game-is-over, depending on whether or not the game has been completed. (2) emits the a-game-is-over event.
> Adding event emission for (1) gamelink and (2) game result parsing. 

- src/subscription.js
Fixes #102.   
Don't share the message between all of the callbacks. :)
> Fixing the error with the message duplication.

- config/config.js
- src/subscription.js
Fixes #110 also add jptriton as a mod
> Adding jptriton fixing 110

- .eslintrc
- src/chesster.js
> Fixing scheduling adding logging

- src/league.js
This allows us to more quickly filter out alternate rows based on
values that are included in column A for alternate rows.
> Filtering out alternate rows.

- src/lichess.js
if the promise exists then the player is already in the queue.
> 117 replace flags for player queue with a map player name->promise. 

- src/league.js
- test/test_league.js
- better date format
- use custom emoji for white and black pieces
Preview:
Requires testing before merge - I haven't done that.
> Improve format of "pairing" command results

- .jshintrc
- .travis.yml
- package.json
- src/chesster.js
- src/commands.js
- src/fuzzy_match.js
- src/gamelinks.js
- src/heltour.js
- src/http.js
- src/league.js
- src/lichess.js
- src/logging.js
- src/models.js
- src/results.js
- src/scheduling.js
- src/slack.js
- src/subscription.js
Added a couple functions that I want to apply across the board.
stripComponents and formatIsValid
These take care of a common idiom that I saw in command parsing of creating variables by name and comparing them to their expected values.
See how they are used and how they simplify some of the code and reduce hardcoding, in a way.
If approved, I will apply across the board.
There are minor changes made across to code base to clean things up after adding jshint.
I also removed some extraneous error checking that should be handled in the middleware.
> availability and jshint

- config/config.js
- src/chesster.js
- src/league.js
Not asking for a review... 
/me is a cowboy :)
> fixing some bugs I found during testing

- config/config.js
- config/testconfig.js
- package.json
- src/chesster.js
- src/league.js
- src/slack.js
- src/subscription.js
1. Made withLeague middleware work with private channels.
2. Use private channel implementation in withLeague for alternate assignment.
3. Added a database migration npm script to package.json
4. Fix date retrieval for pairings.
5. Fix Team name retrieval by player name usage.
> assorted bfs caused from mid season enhancements

- src/chesster.js
I thought I tested the captains stuff but bc I was using the wrong isModerator function (used slack not league), I never actually hit that code.
> Bug in captain alt assignment

- src/commands.js
- test/test_commands.js
> Commandsjs unit tests

- src/chesster.js
- src/league.js
Comparisons against moderators are now lower case. Added handling for results without gamelinks. Moderators can still post results without a link.
> Moderator Fixes / Requests

- src/chesster.js
Adding a notice to the scheduling response to warn users of potential issues with DST
> Attention: The dates above are incorrect during DST transition periods. Please verify your time independently during these times.
> Date notice

- src/chesster.js
Along with a few other permutations that seem relatively natural.
> This should allow the version that is documented to work.

- config/config.js
- config/testconfig.js
- src/watcher.js
Try twice within 10s and we get errors in that context, back off and wait for the next refresh.
> Backoff in the case of errors

- .gitignore
- config/config.js
- config/ladder_config.js.example
- config/testconfig.js
- src/chesster.js
- src/commands/availability.js
- src/commands/games.js
- src/commands/leagueInfo.js
- src/commands/messageForwarding.js
- src/commands/nomination.js
- src/commands/onboarding.js
- src/commands/playerInfo.js
- src/commands/scheduling.js
- src/commands/subscription.js
- src/league.js
- src/logging.js
- src/slack.js
- src/watcher.js
This required a bit more refactoring than I originally anticipated. One
of the things I had to do is refactor the slack module to allow it to
be used more than once, which resulted in my having to touch a lot of
code.  Also, I've had to change it so that we are passing the instance
of our bot object into the .on / .hears callback - so I've had to make
that instance work like the botkit.bot.
>  Initial version of the forwardingMessage command. 

- config/testconfig.js
- src/commands/scheduling.js
As an extra precaution in case someone has the wrong token.
> Disable message forwarding in the test config

- src/slack.js
This will hopefully fix the issue where some user links are randomly ellipsized
> Replace user links in bot.say

- src/commands/availability.js
The argument is supposed to be a team name instead of a team object.
> Fix availability command for captains

- config/config.js
- config/testconfig.js
- test/test_league.js
This mostly just removes the old unused spreadsheet configurations and adds a new configuration for the blitz league.
> Adding a new blitz league.

- src/commands/subscription.js
- src/league.js
This fix allows scheduling messages to be posted in team channels and it also fixes it so that when alternates are used the notifications should work.
> Fix #247 and #243

- src/commands/subscription.js
> Fix some comments and help response

- src/commands/onboarding.ts
> Updating the onboarding messages from chesster

- config/config.js
> changing of phrasing in late scheduling message

- config/config.js
- migrations/20160626215331-adding_subscription_table.js
- migrations/20160626215332-adding_subscription_table_index.js
- package.json
This isn't ready for review yet.
> Integrating with the new 4545 vagrant

- package.json
This time it should be correct :+1:
> Fixes #356

- src/chesster.ts
- src/slack.ts
> Add a 'ping channel' command for league moderators

- src/commands/scheduling.ts
Hello,
I was not able to test this yet, but maybe for such a simple fix the PR could go through.
> fixes #353
